### ISSUE TITLE
Principles of code scaling

### ISSUE THREAD

**Issue by steve-crouch** [Southampton-RSG-Training/dirac-code-scaling-old#1]
Understanding code scalability [Alpha]
Scalability profiling [Alpha]

(Amdahl's Law episode folded into Scalability profiling episode)

**Comment by PipGrylls** [comment]
Understanding code scalability, @steve-crouch 3 days effort, review @EdwardRSE 
Using Amdahl's law, @steve-crouch 2 days effort, review @EdwardRSE 
Scale profiling, @steve-crouch 4 days effort, review @EdwardRSE

**Comment by steve-crouch** [comment]
First content draft complete, based on the expected procedure for DiRAC from Richard Regan. I ended up merging the Amdahl's Law episode into the last one since it covers the Law in-situ with a worked example.

**Comment by steve-crouch** [comment]
Completed.
